#image: ruby:2.4.2
image: docker:18.09.6

stages:
#  - build
  - test
#  - review
#  - stage
  - production

variables:
#  DATABASE_URL: 'mongodb://mongo/user_posts'
  VERSION: '0.1'

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

#build_job:
#  stage: build
#  script:
#    - docker build -t reddit:$VERSION reddit/
#    - docker tag reddit:$VERSION $CI_REGISTRY_USER/otus-reddit:$VERSION
#    - docker push $CI_REGISTRY_USER/otus-reddit:$VERSION

test_unit_job:
  stage: test
#  services:
#    - mongo:latest
#    - ruby:2.4.2
  script:
    - docker run --name reddit --rm -d -p 9292:9292 $CI_REGISTRY_USER/otus-reddit:$VERSION ruby simpletest.rb

#test_integration_job:
#  stage: test
#  script:
#    - echo 'Testing 2'
#
#deploy_dev_job:
#  stage: review
#  script:
#    - echo 'Deploy'
#  environment:
#    name: dev
#    url: http://dev.example.com
#
#branch review:
#  stage: review
#  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
#  environment:
#    name: branch/$CI_COMMIT_REF_NAME
#    url: http://$CI_ENVIRONMENT_SLUG.example.com
#  only:
#    - branches
#  except:
#    - master
#
#staging:
#  stage: stage
#  only:
#    - /^\d+\.\d+\.\d+/
#  when: manual
#  script:
#  - echo 'Deploy'
#  environment:
#    name: stage
#    url: https://beta.example.com

production:
  stage: production
  only:
    - /^\d+\.\d+\.\d+/
  when: manual
  script:
    - export SERVER_IP=35.195.106.41
    - export REPO_NAME=otus-devops-2019-02/dchirkov_microservices
    - export DEPLOY_USER=appuser
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - bundle exec cap production deploy:initial
  environment:
    name: production
    url: http://35.195.106.41:9292
