image: ruby:2.4.2

stages:
  - build
  - test
#  - review
#  - stage
  - production

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'

build_job:
  stage: build
  script:
    - cd reddit
    - bundle install

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

#test_integration_job:
#  stage: test
#  script:
#    - echo 'Testing 2'
#
#deploy_dev_job:
#  stage: review
#  script:
#    - echo 'Deploy'
#  environment:
#    name: dev
#    url: http://dev.example.com
#
#branch review:
#  stage: review
#  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
#  environment:
#    name: branch/$CI_COMMIT_REF_NAME
#    url: http://$CI_ENVIRONMENT_SLUG.example.com
#  only:
#    - branches
#  except:
#    - master
#
#staging:
#  stage: stage
#  only:
#    - /^\d+\.\d+\.\d+/
#  when: manual
#  script:
#  - echo 'Deploy'
#  environment:
#    name: stage
#    url: https://beta.example.com

production:
  stage: production
#  only:
#    - /^\d+\.\d+\.\d+/
  when: manual
  script:
    - export SERVER_IP=35.195.106.41
    - export REPO_NAME=homework/example
    - export DEPLOY_USER=appuser
    - bundle exec cap production deploy:initial
  environment:
    name: production
    url: http://35.195.106.41
