dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: AsUDg6GcDp+JFR4SIfvndr8B8+KtS4VOLqukp9ASf8WWX6vl5msstY7YjDn5UvuQKhFlnDWHUeX+mKhOhR7RcTIvnVMlOeX7N9/C+lN1rMZUBlcv71R8N+9OsFc/jl/Ercvwd0o4g63fAbyE6yn6bJ4elc/44MB0tH1WXA1fYVtjUEPPRu76PRVq17ZeUuzCBTWGwOK7Te8oJnRpwBpo0iDxPKGVlaV9+hGMjgRUrQKD6OiNXgFJJdb5pLIx2R2FXkjVl65MC4nOtdf5P76hnNfOewCTfnej9jD8Pqc2s1e/fHEOPoj5fdJ8VKmtNnwi4vN84O8zNOOCp63jaMqF0QsbAIIo3UOL2e94xl6vpslLGUxt6N42/Lmofuuf2cwsQxOJCqg2WZPM22tJoY5O09Lx9Awjqm4Yn8T0MU2g9K1f9WjtLxVtYKDvpTf7jsuuN9oHzdad5qrdfSM539QmEeuawgxki7fu2m7P2Wq5hFA3JA+hmMJnDw3hOvHSC6xwNSd7kmyNJk/HS1D8l0pqFhj5BC2dr6O1o0ZYeXxg6K0pYyZD1Xvc/Uw3iIXdBhS5UAibq9IgaXIkSwz7iHa+bRidEBXF3CK1m9y1dotCy2AApLhY55feSLoUIH+Q3nhw2mf8Kwl98FFka4eqOIWy8o+1/QrFjJ8gtW3UfuItbLk=
