dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: htfkrEQ0kGsJzXU3SYhzrRuMS4rrmOy56Z+LfymB5kzAJzMOr5YCpkw6gSLkdLaLigXxrRUOPW4dOo//ZcSICH713uNNJoXMrKwDz4cSmtGYURGuieX35ZPvSU0uZFiujT5BlyKfd2BivSgkvurrnXWAXtHWTTOkugrB46mauW6L+e707589pFXTqS9a6bke5yzP76yuTWs+6na0XW9Tl5P/QKsT80zTX+fUzoSb3OFptJ/nePOS2sihw2n9TyTt40DpRYg6iONhU7BhJtP+AGmM4xIu1u9lSwn9Y63tm8uv3o09ToRp5NjeE9/U0KGDWexShPA8S3FpRr9KgzosK5FWDR7uTjqFDET+wZHnoc8EtekVuETMgbynRV2av6DYOVSM8XatoogTyE12x7qT7y2OXEeFQp/TFJ2OOvJvN6bvqcrG1ioBIsxVdNxvpmrsf/Vi4JmLdWEn6+snayFsNvOwe6R3nMov1S8j9sZkj4i477DwMHwlyIxCWRPgOK0EnOS5mdWLYXqij7oA4cP6xvjMBW+QBePV/veQn1OY+ZGuMAXXtKGpxlQEnre4akTwsSMCa2Cq8y1RRQm5jNpTHoSiQoUgOJlonemMOYhqK3ILqFcTqDZfQvvGLdHimNQzoCRp8AYx3RZ0btw92gNVEnAVnjOgVrQI7PtohqCh44s=
