dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: tO4PbpbEd4uKQZ5j0vrFF8JUhAejkQV6wfbYfgD0k9rBEGiW2UwSTYlNxY/3qFUvOHL7QG58DJUU0Y5U+qXfxRGcLeHbJcSBwush2QWoyKRRR++XfLhpHR9PWQutNUlHkUWT1q9mup6W9IIbGA9Bdj0YZzoBaumRs+Gkk9JYBaPU+2jDPNLimu6ZbYUnDZthEs1su4NzhOp8dKL5/qy56PDIo6i5wvW2nNUeZymIdViBhwJqSNAASeUq5aHVWOCxCWPPqZ5NG3m4jgi/IUbS6LQOT8sWNdlM5YZXBPmvFfbmImJQUQZ4Hj/QJqhMBD6IW77IW3Nj36CXMQDz21L19OSkOyN0jW5ST6DV+9tz6FJEcnpkDjRL4bHLxHRSqJfxxL+e5paAPr5frgPPFZXxhMlHnhlutNNB5GskXk8SB2od+VfQblFtvg4jicgO3Q2J/KNYISWo1Ip3CWrNUxqvyacKaU2MutZTtGUGpy8iDz6klHHQuep2oXjqrFQBr7TRrrQZelXmCI5M/CG2Mx2jHGyC2qR3+pL7FEY6I0I/AjzPDdnaxIrU2WPDj1tPycCOXxSirOvbckCxKeHMQ0rDMy5cvM6P3TWSyt19tgJp4GJWlgIh94CIq2G9pGh6XDFrMpNSNYThsZUi4J0xenu/7dy/hlRiwcHIemMo/mexd+0=
