dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: ncv9yuqJG3euUdT8lnsVXT5iz2lQ2bNGXe2/TJ2JvtiLH/ctESShrlFSJC2l/0ZS6pEmxzOzL+BbUpiYsqwcqUCSZttV1yiPW98s8MC1W1q+J8ybnDnG0BijRHhF7uxnxlIp49hcjxRbE2i/ABuw95K3jUTuuYGeI4REfakyBa9Uxx/cLq9V6ICxRpmdK7EF7l2j3mEE+m15xxozMrW+gNC4CO59aadLUJtXBWnBdB1WaIuIoFx26IyCsNd/i2A1/3iYZGK2tPsdyB6wkwiDCVef8f47Cxq3ywHt3URB+p5ev1hMkJVK6POOsyELZja36GUkXMwWTFAV3mkwHwGQZpIi9QfJzg45cnd91EF7Wr+wcdnjn6ZAcysA12GdjD2CRndxRT751+WKgsQeKXtyqrvgWqgwpYkMEXzzkp22hnqnN40I65vF6u+6IY78YW4Ihsmv7hO5I8rF21f7qW2AL3w/DUgTcn39mn7cpdT/ICGdTvG1e1zan2YYhgDF7/0tr/QhHFzBz0GKIRPlGb48GA1tLuP4GGXFYOciH6AKHC0vMARxLh5nsTgsrDMQbSSij43AQ8bvRmZEoTy0z5rzG64afWAAmopFact5LUhIUkGWTC/VryOBjwV/joa65XyP2gsOSf+u+BuhD+AkvZ+caTPJ9E5tM/QWNFUMSM7Wo+I=
