dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: HRQz8aw5lXXv6QE/jO1hOZQZQKGruEBJs0uSg0Ds/niYrtbm7HbzOL2SC/qCd1n40n11EcDGNBU/qJuOOrmMa4JVmYjhuqEdMqI2ii3XUooB7lYCLfZInGQ2XXcndqRtXT+K1JEtjBnUXnyEvrIpz/erb46rRD7jtfSWO+Do77WzLTRPyuTjXlIW4SvqMBXuzUuGvc3FbkXYWYO9EsJzvIr1uDw/hx7jRZvUPLcN2yUn57m3nwSV2mklPqTFwRx6PcX9MOPdVLq05uTHj1pPdmo4+ZsNZgDbURIvC9FOKRQs2xnrZr1KWxWn9x2Ars8lPHrWi3g3GMkJV7VWdqakyMzdcCetqewWKermXfUD43nP3+w9E7iM3k1r4cCMUUXRlHzLbqHXwkz2nLIF4jc7cW5lNLCXSzyGLOmutXVSidCiiLGgDzRCwO9exqnreeVcOX3+zDH2Qkf2w42OADEY9OHqSbcTyfPGfnQXk7HbwZDUKjlzUzCsN6+tvzCjphs0e4i6yocqeAFcGVZMiDHHjRH3smHulBOiIGb0fOOVzJ8BfcXWIfY19xXB7sE11rLZ6TXUsXymv5z9oz55TkxpZw/AwdCWTnO2W0ZUAxaTn32IqD4n/mXA8XxBBPHEpGWbw1Shy65aHJxGhsE2eQtIu9m9m06RkNJ8BxzUrB2NBSA=
