global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitry_chirkov'
