version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      mon_net:
        aliases:
          - mon_post_db

  ui:
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
      mon_net:
        aliases:
          - mon_ui

  post:
    image: ${USERNAME}/post:${VERSION}
    networks:
      front_net:
        aliases:
          - post
      back_net:
      mon_net:
        aliases:
          - mon_post

  comment:
    image: ${USERNAME}/comment:${VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
      mon_net:
        aliases:
          - mon_comment

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      mon_net:
        aliases:
          - mon_prometheus

  node-exporter:
    image: prom/node-exporter:v0.18.0
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      mon_net:
        aliases:
          - mon_node-exporter

  mongodb-exporter:
    image: ${USERNAME}/mongodb-exporter:${VERSION}
    command:
      - '--mongodb.uri=mongodb://post_db:27017'
      - '--collect.database'
      - '--collect.collection'
      - '--collect.topmetrics'
    networks:
      mon_net:
        aliases:
          - mon_mongodb-exporter

  blackbox-exporter:
    image: prom/blackbox-exporter:master
    user: root
    ports:
      - '9115:9115'
    networks:
      mon_net:
        aliases:
          - mon_blackbox-exporter

volumes:
  post_db:
  prometheus_data:

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  mon_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24
