version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      mon_net:
        aliases:
          - mon_post_db

  ui:
    image: ${USER_NAME}/ui:${VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
      mon_net:
        aliases:
          - mon_ui
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USER_NAME}/post:${VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - post
      back_net:
      mon_net:
        aliases:
          - mon_post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    image: ${USER_NAME}/comment:${VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
      mon_net:
        aliases:
          - mon_comment

volumes:
  post_db:

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
  mon_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.3.0/24
