---
- name: Deploy Docker
  hosts: reddit
  gather_facts: no
  become: true
  tasks:
    - name: Install Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable

    - name: Install Docker repository key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        id: 0EBFCD88

    - name: Install Docker
      apt:
        name: "{{ packages }}"
        update_cache: yes
      vars:
        packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - python-pip

    - name: Install docker-machine
      get_url:
        url: https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-Linux-x86_64
        dest: /usr/local/bin/docker-machine
        mode: '0550'

    - name: Enable Docker engine
      systemd:
        name: docker
        state: started
        enabled: yes
