version: '3.3'
services:
  post_db:
    env_file: .env
    image: mongo:3.2
    volumes:
      - post_db:${DP_PATH}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    env_file: .env
    build: ./ui
    image: ${USERNAME}/ui:${VERSION}
    ports:
      - ${REDDIT_PORT}:${REDDIT_PORT}/tcp
    networks:
      - front_net
  post:
    env_file: .env
    build: ./post-py
    image: ${USERNAME}/post:${VERSION}
    networks:
      front_net:
        aliases:
          - post
      back_net:
  comment:
    env_file: .env
    build: ./comment
    image: ${USERNAME}/comment:${VERSION}
    networks:
      front_net:
        aliases:
          - comment
      back_net:

volumes:
  post_db:

networks:
  front_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  back_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
